<a href="https://colab.research.google.com/github/gantavivekkumar/Numpy_notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#what is numpy?
#core librarary for secentific computing in python
#The central object in  numpy is "Numpy Array"
#what is numpy array?
#High performanace multideminsional array object which is designed sepcificall to perform maths operations


In [ ]:
#How many types of array are their?
#1D
#2D
#3D

In [ ]:
#scikit learn,
#matplotlib
#Pandas

In [ ]:
#what are all different use cases and operations that can be achieved easily with numpy
"""1. Dot product/inner product
  2. matrix multiplication,
  3.element wise matrix product
  4.solving the linear systems,
  5.inverse
  6.determinant
  7.choose the random number(gussian/uniform distribution)
  8.statistics """


In [ ]:
#installation
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
#how can we check the numpy version
np.__version__

'1.26.4'

In [ ]:
#diff b/w list and array?
"""array:- array can take homogenous data
           array's are faster than the list becuase these are immutable
           array's having fixed memory """


"array:- array can take homogenous data\n           array's are faster than the list becuase these are immutable\n           array's having fixed memory "

In [ ]:
#diff b/w homogenous and heterogenous data?

CENTRAL OBJECT IS ARRAY

In [ ]:
a = np.array([1,2,3,4])
print(a)
#i want to know the shape of the array
a.shape
#i want to know element data types
a.dtype
#i want to know deminson of array
a.ndim
#i want to know total number elements in array
a.size
#i want to know the size in bytes of each element
a.itemsize

[1 2 3 4]


8

In [ ]:
#central object is an array
#create an 1D array
a = np.array([1,2,3,4,5])
print(a) #[1 2 3 4 5]
# print(type(a))
# check shape of this array
a .shape
#How can you check datatypes of elements in an array
a.dtype
#what is diff b/w int32 and int64
#what is diff b/w float32 and float64
#How can we find the dimensionality of an array?
a.ndim

[1 2 3 4 5]


1

In [ ]:
#How can i see the size of my array? #no. of elements i an array
a.size


5

In [ ]:
#How can i see the size in bytes of each element in an array?
a.itemsize

8

ESSENTIAL METHODS IN AN ARRAY

In [ ]:
b = np.array([1,2,3])
print(b[0])
#replace 1st position with 5
b[0] = 5
print(b)
#do element wise math operations
c = b * np.array([2,0,2])
print(c)

1
[5 2 3]
[10  0  6]


ARRAY VS LIST

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
d = np.array(l)
print(l)
print(d)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#add an item at the end of the list
l.append(10)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#add item at the end of an array?
# d.append(10) ---> it rises an error
# print(d)
#there are ways to add the items in the array, but this esseentiall creates a new array
# l2 = l + [11]
# print(l2)

a2 = d + np.array([10])
print(a2)

[11 12 13 14 15 16 17 18 19]


In [ ]:
#Vector addition:- adding the vectores of same size
#we cannot add the vectors of same size
a3 = d + np.array([1,2,3,4,5,6,7,8,9])
print(a3)



[ 2  4  6  8 10 12 14 16 18]


In [ ]:
#Multiplication
#how can we do multiplication of each element in an array?
a1 = np.array([1,2,3,4,5])
print(a1*2)

[ 2  4  6  8 10]


In [ ]:
#modify each item in a list and store it in new list do thw muliply with 2 in given list
#[2,4,6,8,10]
#output: [4,8,12,16,20]
list = [2,4,6,8,10]
new_list = []
for i in list:
    new_list.append(i*2)
print(new_list)

[4, 8, 12, 16, 20]


In [ ]:
#print sqr of array a1?
print(a1)
print(a1**2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [ ]:
#print of sqrt of a1?
# print(a1**0.5)
np.exp(a1)
# np.tanh(a1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
#how to find log of a1 by usinh numpy
d1 = np.log(a1)
print(d1)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
a = np.array([1,2])
b = np.array([3,4])
#sum of the produucts of the corresponding entries
#multiply each corresponding element and then take the sum
#cumbersome way of lists
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
print(dot)

11


In [ ]:
#same thing in numpy
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#step by step procedure
c = a * b
print(c)
d = np.sum(c)
print(d)

[3 8]
11


In [ ]:
dot = a.dot(b)
print(dot)

11


In [ ]:
dot = (a * b).sum()
print(dot)

11


In [ ]:
#in newer version
dot = a @ b
print(dot)

11


ARRAY VS LIST SPEED TEST

In [ ]:
import numpy as np

In [ ]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
# print(a)
# print(b)
A = list(a)
B = list(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(A)):
    dot += A[i] * B[i]
  return dot
def dot2():
  return np.dot(a,b)

#calculate time of execution
start = timer()
for t in range(T):
  dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end - start

print('time with lists',t1)
print('time with array',t2)
print('ratio', t1/t2)

MULTIDIMENSIONAL ARRAY

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[[1 2]
 [3 4]]
(2, 2)
2
4
int64


In [ ]:
#access the elements -->(rows,columns)
print(a[0]) #---> [1 2]
print(a[0,1])
#print the 4 element
print(a[1,1])

[1 2]
2
4


In [ ]:
#print the all rows in column 0
print(a[:,0])

[1 3]


In [ ]:
#print all the columns in row 0?
print(a[0,:])


[1 2]


In [ ]:
#print all rows in column 1?
print(a[:,1])

[2 4]


In [ ]:
#print all the columns in row1?
print(a[1,:])

[3 4]


In [ ]:
#Transpose  -->columns change into rows and rows change in to columns
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
#matrix multiplication with dot
b = np.array([[3,4],[5,6]])
c = a.dot(b)
print(c)

[[13 16]
 [29 36]]


In [ ]:
#Determinant finding
#find the det of c?
c = np.linalg.det(a)
print(c)

-2.0000000000000004


In [ ]:
#find the diagonal of a?
c = np.diag(a)
print(c)

[1 4]


In [ ]:
#print inverse of array a?
c = np.linalg.inv(a)
print(c)
#https://www.tutorialspoint.com/numpy/numpy_inv.htm#:~:text=We%20use%20numpy.,it%20results%20in%20identity%20mat


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#diag on a vector returns returns diagonal matrix(overloaded function)
c = np.diag([1,4])
print(c)

[[1 0]
 [0 4]]


INDEXING AND SLICING ,BOOLEAN INDEXING

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
# print(a.shape)
# print(a.ndim)
# print(a.size)
# print(a.dtype)
print(a[0,::])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [ ]:
#print 1st column---<159
print(a[:,0])

[1 5 9]


In [ ]:
#slice [2,3 and 6,7] from above array
s = a[0:2,1:3]
print(s)

[[2 3]
 [6 7]]


In [ ]:
print(a[-1,-2]) #---- -ve row from reverse direction "-1" and -ve column in last position "-1"

11


In [ ]:
#Boolean indexing
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#print the values "true" if it is greater than 2 else false.
print(a > 2)
#note:- this will be a rank 1 array

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
#iwant values greater than 2
print(a[a>2])
print(a[a>2].shape)

[3 4 5 6]
(4,)


In [ ]:
#please go through rank1 and rank2 arrays--->HW

#np.where():- same size with modifed values
b = np.where(a>2,a,-1) #(condtion,array,values to be passed)
print(b)


[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
#Fnacy Indexing:- with this indexing you can access multiple indices at once
a = np.array([10,19,30,41,50,61])
b = a[[1,3,5]]
print(b)

[19 41 61]


In [ ]:
#compute indices whwre the condition true?
even = np.argwhere(a % 2 == 0).flatten()
print(even)

[0 2 4]


RESHAPING

In [ ]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [ ]:
#reshape(row,col)
c = a.reshape(3,2)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#newax:- is used to create a new axis in the data [row,:col]
#it is requiered when model require the data to be shaped in a certain manner
print(a.shape)

(6,)


In [ ]:
d = a[np.newaxis,:]   #[row(newaxis),:]
print(d)
print(d.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
e = a[:,np.newaxis]   #[row(fefault(:)), col[newaxis]]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


CONCATENATION

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#conbine this array's into 1d array
# c =np.concatenate((a,b), axis =None)
# print(c)
# #axis = 0
# d =np.concatenate((a,b), axis =0)
# print(d)
# #give axis = 1
e =np.concatenate((a,b), axis =1)
print(e)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#add new column in to array:- note we have to transpose it
c = np.concatenate((a,b.T),axis = 1)
print(c)
print(b.T)

[[1 2 5]
 [3 4 6]]
[[5]
 [6]]


In [ ]:
#hstack:- stack of arrays in sequence horizentally(column wise) need a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)
#please try with "np.concatenate(a,b, axis = None)"

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vstack:-
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


BROADCASTING

In [ ]:
"""it is a powerfull mechanism that allows numpy arrays to work with different shapes
when performing arthamatic operations"""
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,1])  #add y to each row of x using the braod casting
z = x + y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


FUNCTION AND AXIS

In [ ]:
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
#sum of the above array
print(a.sum())
#use axis = None
print(a.sum(axis = None))
#use axis = 0
print(a.sum(axis = 0))
#use axis = 1
print(a.sum(axis = 1))
#claculate mean with axis None, 0, 1
print(a.mean(axis = None))
print(a.mean(axis = 0))
print(a.mean(axis = 1))

210
210
[24 26 28 30 32 34 36]
[ 70 140]
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


DATA TYPES

In [ ]:
x = np.array([1,2])
print(x.dtype)

int64


In [ ]:
#let np choose datatypes
x = np.array([1.0,2.0])
print(x.dtype)

float64


In [ ]:
#force a data type how many bits you want (how precise)
x = np.array([1,2], dtype = np.int32)
print(x.dtype)

int32


In [ ]:
x = np.array([1,2], dtype = np.float32)
print(x.dtype)

float32


In [ ]:
x = np.array([1,2], dtype = np.float32)
print(x.dtype)

float32


COPYING

In [ ]:
a = np.array([1,2,3])
b = a   #only copies references
b[0] = 42
print(a)

[42  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy() #actaula copy
b[0] = 46
print(a)

[1 2 3]


GENARATING ARRAYS

In [ ]:
#print zeros in 2 rows and 3 columns
a = np.zeros((2,3))
print(a)
#specific  numbner of matrix in 3 rows and 3 columns
c = np.full((3,3),(5))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#print identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#linspace  #we are using this command to separate the given data in to specific numbers
f = np.linspace(0,10,5)
print(f)

[ 0.   2.5  5.   7.5 10. ]


RANDOM NUMBERS


In [ ]:
a = np.random.random((3,2))   #uniform 0-1 distribution
print(a)

[[0.49868417 0.96244264]
 [0.34073939 0.24160953]
 [0.48129388 0.57009073]]


In [ ]:
b = np.random.randn(3,2)  #normal/gussian distribution, mean 0 and unit veriance.
print(b)

[[-1.19216325  0.77253562]
 [ 2.67641989 -1.22064925]
 [-0.09914731 -0.14567571]]


In [ ]:
c = np.random.randn(100000)
print(c.mean(),c.var(),c.std())

-0.0015520596879529103 0.9972946162185128 0.9986463919819231


In [ ]:
d = np.random.randn(10,3)

print(d.mean())

-0.02490660802517508


In [ ]:
d = np.random.randint(3,10, size=(3,3))
print(d)

[[6 3 8]
 [7 3 9]
 [6 4 4]]


In [ ]:
#with integer is between 0 up to interger exclusive
f = np.random.choice(10, size = 8)
print(f)

[9 8 6 3 5 1 1 3]


In [ ]:
f = np.random.choice([1,2,3,4], size = 8)
print(f)

[1 4 1 4 2 4 2 3]


#  #Linear Algebra (Eigenvalues/solving linear systems)

In [ ]:
a = np.array([[1,2],[3,4]])
# print(a)
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)  #column vectors

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
print(eigenvectors[:,0])

[-0.82456484  0.56576746]


In [ ]:
#How can we verify the eigenvalues and eigen vectors
#A)e-vec * e- val = a * e-vector
d = eigenvectors[:,0]*eigenvalues[0]
e = a @ eigenvectors[:,0]
print(d)
print(e)
# print(d == e)
#correct way to compare matrix
print(np.allclose(d,e))

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
True


In [ ]:
#solving the linera systems
# x1 + x2 = 2200
# 1.5 x1 +  4 x2 = 5050
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])
# Ax = b <=> x = A - 1 b
#sloving inverse is slow and less accurate
x = np.linalg.inv(A).dot(B)  #Not recommended method
print(x)
#instead use
x = np.linalg.solve(A,B)
print(x)


[1500.  700.]
[1500.  700.]


LOADING A CSV FILE

In [ ]:
#load it with np.loadtxt()
data = np.loadtxt("/content/sample_data/california_housing_test.csv",delimiter = ",",dtype = str)
print(data.shape,data.dtype)

(3001, 9) <U20


In [ ]:
data = np.genfromtxt("/content/sample_data/california_housing_test.csv",delimiter = ",",dtype = str)
print(data.shape,data.dtype)

(3001, 9) <U20
